# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Name   : makefile
# Author : Amane Chibana
# Pledge : I pledge my honor that I have abided by the Stevens Honor System.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

CC=gcc

all:
	$(CC) server.c -o server
	$(CC) client.c -o client
